app_default:
    resource: "@AppBundle/Ressources/config/routing/default.yml"
    prefix: /
app_user:
    resource: "@AppBundle/Ressources/config/routing/user.yml"
    prefix: /user
app_video:
    resource: "@AppBundle/Ressources/config/routing/video.yml"
    prefix: /video